/* USER REDUCER TYPES */
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

export const SET_POSTS = "SET_POSTS";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_ADVISORS = "SET_ADVISORS";
export const SET_POST = "SET_POST";
